# .github/workflows/deploy_to_hf.yml
name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-space:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # We need to fetch all history for proper versioning
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone Hugging Face Space repository
        run: |
          # Use your HF username and the name of your Space
          # The HF_TOKEN is a secret you set in your GitHub repo settings
          git clone https://ashandilgith:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/ashandilgith/enginevibration space-repo

      - name: Copy new files to Space repo
        run: |
          # This command copies the essential files for the app to run.
          # It excludes development files like .git, .github, and the space-repo clone.
          rsync -av --delete --exclude='.git/' --exclude='.github/' --exclude='space-repo/' ./ space-repo/

      - name: Commit and push to Space
        run: |
          cd space-repo
          git add .
          # Check if there are any changes to commit
          if ! git diff-index --quiet HEAD; then
            git commit -m "Deploy from GitHub Actions"
            git push
          else
            echo "No changes to deploy."
          fi
